# Generated by Django 3.0.1 on 2019-12-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191219_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='date_time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
